name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-formulas:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Homebrew on Linux
        if: runner.os == 'Linux'
        uses: Homebrew/actions/setup-homebrew@master

      - name: Update Homebrew
        run: brew update

      - name: Brew audit
        run: |
          for f in Formula/*.rb; do
            formula_name="$(basename "$f" .rb)"
            echo "Auditing $formula_name"
            brew audit "$formula_name" || exit 1
          done

      - name: Install formulas
        run: |
          # First install only dependencies
          for f in Formula/*.rb; do
            brew install --build-from-source --only-dependencies "$f" || exit 1
          done
          # Then install the formulas themselves
          for f in Formula/*.rb; do
            echo "Installing $(basename "$f")"
            brew install --build-from-source "$f" || exit 1
          done

      - name: Run tests
        run: |
          for f in Formula/*.rb; do
            formula_name="$(basename "$f" .rb)"
            echo "Testing $formula_name"
            brew test "$formula_name" || echo "Warning: Test failed for $formula_name but continuing"
          done
