name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-formulas:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Homebrew on Linux
        if: runner.os == 'Linux'
        uses: Homebrew/actions/setup-homebrew@master

      - name: Brew audit
        run: brew audit --strict --online ./Formula/*.rb

      - name: Install formulas
        run: |
          for f in Formula/*.rb; do
            brew install --build-from-source "$f"
          done

      - name: Run tests
        run: |
          for f in Formula/*.rb; do
            brew test "$(basename "$f" .rb)"
          done
